const url = "http://localhost/index.php"
Cypress.config('chromeWebSecurity', false); 
describe('template spec',() =>{
  it('TC1',()=>{
    //อนุมัติ
    cy.visit(url) 
    cy.get(':nth-child(3) > a > span').click()
    cy.get('#login_username').type('Admin')
    cy.get('#login_password').type('admin')
    cy.get('.button').click()
    cy.wait(1000)
    cy.get('.report > a > span').click()
    cy.get('#datatable_1 > .buttons > .button').click()
    cy.get('#status').select('1')
    cy.get('#reason').type('เห็นชอบ')
    cy.get('.button').click({ force: true })
  })
  it('TC2',()=>{
    //ไม่อนุมัติ
    cy.visit(url) 
    cy.get(':nth-child(3) > a > span').click()
    cy.get('#login_username').type('Admin')
    cy.get('#login_password').type('admin')
    cy.get('.button').click()
    cy.wait(1000)
    cy.get('.report > a > span').click()
    cy.get(':nth-child(7) > label > select').select('0')
    cy.get(':nth-child(9) > .button').click()
    cy.get('#datatable_2 > .buttons > .button').click()
    cy.get('#status').select('2')
    cy.get('#reason').type('ไม่เห็นชอบ')
    cy.get('.button').click({ force: true })
  })
  it('TC3',()=>{
    //ผู้จองยกเลิก
    cy.visit(url) 
    cy.get(':nth-child(3) > a > span').click()
    cy.get('#login_username').type('Admin')
    cy.get('#login_password').type('admin')
    cy.get('.button').click()
    cy.wait(1000)
    cy.get('.report > a > span').click()
    cy.get(':nth-child(7) > label > select').select('0')
    cy.get(':nth-child(9) > .button').click()
    cy.get('#datatable_3 > .buttons > .button').click()
    cy.get('#status').select('3')
    cy.get('#reason').type('ผู้จองเปลี่ยนใจ')
    cy.get('.button').click({ force: true })
  })
  it('TC4',()=>{
    //ยกเลิกโดยเจ้าหน้าที่
    cy.visit(url) 
    cy.get(':nth-child(3) > a > span').click()
    cy.get('#login_username').type('Admin')
    cy.get('#login_password').type('admin')
    cy.get('.button').click()
    cy.wait(1000)
    cy.get('.report > a > span').click()
    cy.get(':nth-child(7) > label > select').select('0')
    cy.get(':nth-child(9) > .button').click()
    cy.get('#datatable_4 > .buttons > .button').click()
    cy.get('#status').select('4')
    cy.get('#reason').type('ห้องประชุมอยู่ในการปรับปรุง')
    cy.get('.button').click({ force: true })
  })
  it('TC5',()=>{
    //อนุมัติโดยวันเวลาซ้ำกัน
    cy.visit(url) 
    cy.get(':nth-child(3) > a > span').click()
    cy.get('#login_username').type('Admin')
    cy.get('#login_password').type('admin')
    cy.get('.button').click()
    cy.wait(1000)
    cy.get('.report > a > span').click()
    cy.get(':nth-child(7) > label > select').select('0')
    cy.get(':nth-child(9) > .button').click()
    cy.get('#datatable_8 > .buttons > .button').click()
    cy.get('#status').select('1')
    cy.get('#reason').type('เห็นชอบ')
    cy.get('.button').click({ force: true })
    cy.get('.report > a > span').click()
    cy.get(':nth-child(7) > label > select').select('0')
    cy.get(':nth-child(9) > .button').click()
    cy.get('#datatable_9 > .buttons > .button').click()
    cy.get('#status').select('1')
    cy.get('#reason').type('เห็นชอบ')
    cy.get('.button').click({ force: true })
  })
})